# Generated by Django 3.2.6 on 2024-10-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_no',
            field=models.BigIntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emrg_contact_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='history',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_time', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
            ],
        ),
    ]
