# Generated by Django 4.1.13 on 2024-10-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241014_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='eid',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='WorkDetails',
        ),
    ]
